-- Tabela EMPRESA
CREATE TABLE EMPRESA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    nome_razao_social VARCHAR(255) NOT NULL
);

-- Tabela EMPRESA_ENDERECO
CREATE TABLE EMPRESA_ENDERECO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    complemento VARCHAR(255),
    cep VARCHAR(9) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    CONSTRAINT fk_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES EMPRESA(id)
        ON DELETE CASCADE
);


-- Tabela PESSOA
CREATE TABLE PESSOA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    empresa_id BIGINT NOT NULL,
    CONSTRAINT fk_pessoa_empresa
        FOREIGN KEY (empresa_id) REFERENCES EMPRESA (id)
        ON DELETE CASCADE
);