CREATE TABLE ADM (
    KEY_ID VARCHAR(100) PRIMARY KEY,
    VALUE_DATA VARCHAR(255) NOT NULL
);


-- Tabela EMPRESA
CREATE TABLE EMPRESA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    nome_razao_social VARCHAR(255) NOT NULL
);

-- Tabela EMPRESA_ENDERECO
CREATE TABLE EMPRESA_ENDERECO (
    empresa_id BIGINT NOT NULL,
    id BIGINT NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    complemento VARCHAR(255),
    cep VARCHAR(9) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    PRIMARY KEY (empresa_id, id),
    FOREIGN KEY (empresa_id) REFERENCES EMPRESA(id)
);

-- Tabela PESSOA
CREATE TABLE PESSOA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(100),
    empresa_id BIGINT,
    FOREIGN KEY (empresa_id) REFERENCES EMPRESA(id)
);
